---
title: "STAT696 Discussion"
author: "Andrew Bates, Josh Gloyd"
header-includes:
  - \usepackage{themes/beamertheme696}
output: beamer_presentation
---


## How to Display Data Badly

```{r, fig.height=3, echo=FALSE}
library(png)
library(grid)
img_bad = readPNG("/Users/joshua_331/GitTemp/STAT696_Discussion/Discussion Slides/images/bad_plot.png")
grid.raster(img_bad)
```

<!-- slide 3 -->

## Discussion Points

>- Why display data?
>- What can go wrong?
>     - Actually display the data
>     - Don't be deceptive
>     - Be consistent
>- Keep it simple  


<!-- slide 4 -->

## How to Display Data Well

```{r, fig.height=3, echo=FALSE}
img_good = readPNG("/Users/joshua_331/GitTemp/STAT696_Discussion/Discussion Slides/images/good_plot.png")
grid.raster(img_good)
```

<!-- slide 5 -->

## References

- Wainer, Howard. *How to Display Data Badly*. The American Statistician Vol. 38, No. 2, (1984), pp. 137-147

- Asher, Jeff. *A Rise in Murder? Let's Talk About the Weather*. New York Times Online, Sep. 21, 2018.

